attendance_checker/urls.py
from django.contrib import admin
from django.urls import path,include
from core import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('',views.index,name='index'),
    path('', include('core.urls')),
]

core/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('<str:username>/', views.home, name='home'),
    path('<str:username>/delete-profile/', views.delete_profile, name='delete_profile'),
    path('<str:username>/log-out/', views.log_out, name='log_out'),
    path('<str:username>/edit-profile/', views.edit_profile, name='edit_profile'),
    path('<str:username>/change-username/', views.change_username, name='change_username'),
    path('<str:username>/change-email/', views.change_email, name='change_email'),
    path('<str:username>/change-password/', views.change_password, name='change_password'),
    path('<str:username>/add-course/', views.add_course, name='add-course'),
    path('<str:username>/<str:coursename>/', views.view_course, name='view_course'),
    path('<str:username>/<str:coursename>/delete-course/', views.delete_course, name='delete_course'),
    path('<str:username>/<str:coursename>/add-class/', views.add_class, name='add_class'),
    path('<str:username>/<str:coursename>/<str:classname>/', views.view_class, name='view_class'),
    path('<str:username>/<str:coursename>/<str:classname>/delete-class/', views.delete_class, name='delete_class'),
    path('<str:username>/<str:coursename>/<str:classname>/add-event/', views.add_event, name='add_event'),
    path('<str:username>/<str:coursename>/<str:classname>/<int:event_id>/delete-event/', views.delete_event, name='delete_event'),
    path('<str:username>/<str:coursename>/<str:classname>/<int:event_id>/checkin/', views.check_in, name='check_in'),
    path('check_in_not_allowed/', views.check_in_not_allowed, name='check_in_not_allowed'),
    path('<str:username>/<str:coursename>/<str:classname>/<int:event_id>/view-event/', views.view_event, name='view_event'),
   
]

core/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import User
from django_google_maps.fields import AddressField, GeoLocationField  
from django.utils.translation import gettext_lazy as _


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
  
    
    
    def __str__(self):
        return self.user.username

class Course(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    lecturer_profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Class(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    class_name = models.CharField(max_length=100)

    def __str__(self):
        return self.class_name    

class Event(models.Model):
    event_id = models.AutoField(primary_key=True)
    related_class = models.ForeignKey(Class, on_delete=models.CASCADE)
    event_name = models.CharField(max_length=100, blank=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location_address = models.CharField(max_length=200,null=True, blank=True)
    radius = models.DecimalField(max_digits=5, decimal_places=2)
    is_student_id_required = models.BooleanField(default=False)
    is_index_number_required = models.BooleanField(default=False)
    is_student_name_required = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    checkpoint_lat = models.DecimalField(decimal_places=7, max_digits=15, null=True)
    checkpoint_lng =  models.DecimalField(decimal_places=7, max_digits=15, null=True) 
    def __str__(self):
        if self.event_name:
            return self.event_name
        else:
            return f"Event ID: {self.event_id}" 
    
    class Meta:
        ordering = ['-created_at']

    
class CheckIn(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    student_id = models.CharField(max_length=100, blank=True, null=True)
    index_number = models.CharField(max_length=100, blank=True, null=True)
    student_name = models.CharField(max_length=100, blank=True, null=True)
    check_in_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"CheckIn for {self.event}"    

core/views.py
from django.shortcuts import render, redirect, get_object_or_404,HttpResponse
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import LoginForm
from django.contrib.auth import authenticate,update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import pandas as pd
from . models import CheckIn, Profile, Course, Class,Event
from .forms import CourseForm, EventForm, ClassForm,ChangePasswordForm,UsernameChangeForm,EmailChangeForm,CheckInForm
from django.http import HttpRequest
from math import radians, sin, cos, sqrt, atan2



def index(request):
    context = {
        'title': 'WhereAreYou',
    }
    return render(request, 'core/index.html', context)

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        
        if password == password2:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username Taken')
                return redirect('signup')
            else:
                # Create the user
                user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name, email=email, password=password)
                
                # Create the profile for the user
                Profile.objects.create(user=user)
                
                messages.success(request, 'Account created successfully. Please log in.')
                return redirect('login')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('signup')
    else:
        return render(request, 'core/signup.html')
    
@login_required
def edit_profile(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    
    return render(request, 'core/edit_profile.html', {'profile': profile})

@login_required
def change_username(request, username):
    user = request.user
    if request.method == 'POST':
        form = UsernameChangeForm(request.POST, instance=user)
        if form.is_valid():
            new_username = form.cleaned_data['username']
            if User.objects.filter(username=new_username).exclude(pk=user.pk).exists():
                messages.error(request, 'Username is already taken. Please choose a different one.')
            else:
                form.save()
                return redirect('edit_profile', username=username)
    else:
        form = UsernameChangeForm(instance=user)
    return render(request, 'core/change_username.html', {'form': form})

@login_required
def change_email(request, username):
    user = request.user
    if request.method == 'POST':
        form = EmailChangeForm(request.POST, instance=user)
        if form.is_valid():
            new_email = form.cleaned_data['email']
            if User.objects.filter(email=new_email).exclude(pk=user.pk).exists():
                messages.error(request, 'Email is already taken. Please choose a different one.')
            else:
                form.save()
                return redirect('edit_profile', username=username)
    else:
        form = EmailChangeForm(instance=user)
    return render(request, 'core/change_email.html', {'form': form})


@login_required
def change_password(request, username):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(user, request.POST)
        if form.is_valid():
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']
            if password1 == password2:
                user = form.save()
                update_session_auth_hash(request, user)  # Important to maintain session
                messages.success(request, 'Your password was successfully updated!')
                return redirect('edit_profile', username=username)
            else:
                messages.error(request, 'Passwords do not match')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = ChangePasswordForm(user)
    return render(request, 'core/change_password.html', {'form': form})
    
@login_required
def delete_profile(request, username):
    profile = get_object_or_404(Profile, user__username=username)
    if request.method == 'POST':
        profile.delete()
        messages.success(request, 'Profile and all related data deleted successfully.')
        return redirect('signup')
    return render(request, 'core/delete_profile.html', {'profile': profile})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_login(request, user)
                # Retrieve the Profile instance for the authenticated user
                try:
                    profile = Profile.objects.get(user=user)
                except Profile.DoesNotExist:
                    # Handle the case where profile does not exist (create if necessary)
                    profile = Profile.objects.create(user=user)
                # Redirect to 'home' passing the username as an argument
                return redirect('home', username=profile.user.username)
            else:
                form.add_error(None, 'Invalid username or password')
    else:
        form = LoginForm()
    return render(request, 'core/login.html', {'form': form})

@login_required
def log_out(request, username):
    if request.method == 'POST':
        auth_logout(request)
        return redirect('login')
    return render(request, 'core/log_out.html')

# @login_required
# def home(request, username):
#     print(username)
#     user = User.objects.get(username='bmwdoame')

def home(request, username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user__username=username)
    courses = Course.objects.filter(lecturer_profile=profile)
    context = {'profile': profile, 'courses': courses}
    return render(request, 'core/home.html', context)

def add_course(request, username):
    profile = Profile.objects.get(user__username=username)
    if request.method == 'POST':
        form = CourseForm(request.POST)
        if form.is_valid():
            course_name = form.cleaned_data['name']
            if Course.objects.filter(name=course_name, lecturer_profile=profile).exists():
                messages.error(request, f'A course with the name "{course_name}" already exists for your profile.')
            else:
                course = form.save(commit=False)
                course.lecturer_profile = profile
                course.save()
                messages.success(request, f'Course "{course_name}" created successfully.')
                return redirect('home', username=username)
    else:
        form = CourseForm()
    return render(request, 'core/add_course.html', {'form': form})

@login_required
def delete_course(request, username, coursename):
    profile = get_object_or_404(Profile, user__username=username)
    course = get_object_or_404(Course, name=coursename, lecturer_profile=profile)
    if request.method == 'POST':
        course.delete()
        messages.success(request, 'Course and all related data deleted successfully.')
        return redirect('home', username=username)
    return render(request, 'core/delete_course.html', {'course': course})

# def view_event(request, event_id):
#     event = Event.objects.get(event_id=event_id)
#     context =  {'event': event}
#     return render(request, 'core/view_event.html', context)

@login_required
def view_course(request, username, coursename):
    profile = Profile.objects.get(user__username=username)
    course = get_object_or_404(Course, name=coursename, lecturer_profile=profile)
    classes = Class.objects.filter(course=course)
    return render(request, 'core/view_course.html', {'course': course, 'classes': classes})

# Class Views
def add_class(request, username, coursename):
    if request.method == 'POST':
        form = ClassForm(request.POST)
        if form.is_valid():
            course = get_object_or_404(Course, name=coursename)
            class_name = form.cleaned_data['class_name']
            if Class.objects.filter(course=course, class_name=class_name).exists():
                messages.error(request, 'A class with this name already exists for this course.')
            else:
                form.instance.course = course
                
                form.save()
                return redirect('view_course', username=username, coursename=coursename)
    else:
        form = ClassForm()
    return render(request, 'core/add_class.html', {'form': form})

@login_required
def delete_class(request, username, coursename, classname):
    class_obj = get_object_or_404(Class, course__name=coursename, class_name=classname)
    if request.method == 'POST':
        class_obj.delete()
        messages.success(request, 'Class and all related data deleted successfully.')
        return redirect('view_course', username=username, coursename=coursename)
    return render(request, 'core/delete_class.html', {'class_obj': class_obj})

def view_class(request: HttpRequest, username, coursename, classname):
    print(coursename)
    # Get the class based on username, coursename, and classname
    #profile = Profile.objects.get(user__username=username)

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    spacing: {
                        '128': '32rem',e 
                    }
                }
            }
        }
    </script>
    <title>{% block title %}{% endblock title %} | WhereAreYou</title>
    <style>
        dd {
            background-color: rgb(19, 108, 143);
        }
    </style>
</head>
<body class="relative">
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold"><small style="font-family:Calibri">W<b>H</b>ere</small>Are<i>YOU</i></a>
        <div class="space-x-6">
            {% if request.user.is_authenticated %}
            <button id="sidebarToggle" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">{{ user.username }}</button>
            {% else %}
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
            <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Sign in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500"> You would like it here</p>
        </div>
        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class=" text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="#" class=" text-lg text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                <li><a href="#" class=" text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class=" text-lg text-teal-500 hover:text-teal-700">Terms of use</a></li>
            </ul>
        </div>
    </footer>
     
    <!-- Sidebar -->
    {% if user.is_authenticated %}
    <div id="sidebar" class="fixed top-0 right-0 w-64 h-full bg-gray-800 transform translate-x-full transition-transform">
        <div class="py-6 px-6">
            <button id="sidebarClose" class="mb-6 text-white text-2xl">&times;</button>
            <nav class="space-y-4">
                <a href="{% url 'home' request.user.username %}" class="block text-white text-lg">My Home</a>
                <a href="{% url 'home' request.user.username %}" class="block text-white text-lg">My Courses</a>
                <a href="{% url 'edit_profile' request.user.username %}" class="block text-white text-lg">Edit Profile</a>
                <a href="{% url 'log_out' request.user.username %}" class="block text-white text-lg">Log Out</a>
            </nav>
        </div>
    </div>
    {% endif %}
    <script>
        document.getElementById('sidebarToggle').addEventListener('click', function() {
            document.getElementById('sidebar').classList.toggle('translate-x-full');
        });
        document.getElementById('sidebarClose').addEventListener('click', function() {
            document.getElementById('sidebar').classList.add('translate-x-full');
        });
    </script>
</body>
</html>

core/templates/core/change_email.html
<!-- templates/core/change_email.html -->
{% extends 'core/base.html' %}
{% block title %}Change Email{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Change Email</h2>
    <form method="post">
        {% csrf_token %}
        {% if messages %}
            <div class="text-red-500">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Change Email</button>
    </form>
</div>
{% endblock %}

core/templates/core/change_username.html
<!-- templates/core/change_username.html -->
{% extends 'core/base.html' %}
{% block title %}Change Username{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Change Username</h2>
    <form method="post">
        {% csrf_token %}
        {% if messages %}
            <div class="text-red-500">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        {{ form.as_p }}
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Change Username</button>
    </form>
</div>
{% endblock %}

core/templates/core/check_in.html
{% extends 'core/base.html' %}
{% block title %}Check-In{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Check-In</h2>
    <form id="check-in-form" method="post">
        {% csrf_token %}
        {% if is_student_id_required %}
        <div class="mb-6">
            <label class="block mb-2" for="id_student_id">Student ID</label>
            {{ form.student_id }}
        </div>
        {% endif %}
        {% if is_index_number_required %}
        <div class="mb-6">
            <label class="block mb-2" for="id_index_number">Index Number</label>
            {{ form.index_number }}
        </div>
        {% endif %}
        {% if is_student_name_required %}
        <div class="mb-6">
            <label class="block mb-2" for="id_student_name">Student Name</label>
            {{ form.student_name }}
        </div>
        {% endif %}
        <input type="hidden" id="latitude" name="latitude">
        <input type="hidden" id="longitude" name="longitude">
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Check-In</button>
    </form>
</div>
<script>
window.onload = function() {
    getLocation();
}

function getLocation() {
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition, showError);
    } else {
        alert("Geolocation is not supported by this browser.");
    }
}

function showPosition(position) {
    var latitude = position.coords.latitude;
    var longitude = position.coords.longitude;
    document.getElementById("latitude").value = latitude;
    document.getElementById("longitude").value = longitude;
}

function showError(error) {
    switch(error.code) {
        case error.PERMISSION_DENIED:
            alert("User denied the request for Geolocation.");
            break;
        case error.POSITION_UNAVAILABLE:
            alert("Location information is unavailable.");
            break;
        case error.TIMEOUT:
            alert("The request to get user location timed out.");
            break;
        case error.UNKNOWN_ERROR:
            alert("An unknown error occurred.");
            break;
    }
}
</script>
{% endblock %}

core/templates/core/check_in_not_allowed.html
{% extends 'core/base.html' %}
{% block title %}Check-In Not Allowed{% endblock title %}
{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="bg-white p-8 rounded-lg shadow-lg max-w-md text-center">
        <h1 class="text-3xl font-bold text-red-600 mb-4">Check-In Not Allowed</h1>
        <p class="text-gray-700 mb-6">{{ message }}</p>
        <a href="javascript:history.back()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Try Again</a>
    </div>
</div>
{% endblock %}

core/templates/core/check_in_success.html
<!-- templates/core/check_in_success.html -->
{% extends 'core/base.html' %}
{% block title %}Check-In Success{% endblock title %}
{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-100">
    <div class="bg-white p-8 rounded-lg shadow-lg max-w-md text-center">
        <h1 class="text-3xl font-bold text-green-600 mb-4">Check-In Successful</h1>
        <p class="text-gray-700 mb-6">You have successfully checked in to the event.</p>
    </div>
</div>
{% endblock %}

core/templates/core/delete_class.html
{% extends 'core/base.html' %}
{% block title %}Delete Class{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Delete Class</h2>
    <p>Are you sure you want to delete this class: {{ class_obj.class_name }}? This action cannot be undone.</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Proceed</button>
        <a href="{% url 'view_course' username=request.user.username coursename=class_obj.course.name %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>
    </form>
</div>
{% endblock %}

core/templates/core/delete_course.html
{% extends 'core/base.html' %}
{% block title %}Delete Course{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Delete Course</h2>
    <p>Are you sure you want to delete this course: {{ course.name }}? This action cannot be undone.</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Proceed</button>
        <a href="{% url 'view_course' username=request.user.username coursename=course.name %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>
    </form>
</div>
{% endblock %}

core/templates/core/delete_event.html
{% extends 'core/base.html' %}
{% block title %}Delete Event{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Delete Event</h2>
    <p>Are you sure you want to delete this event: {{ event.event_name }}? This action cannot be undone.</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Proceed</button>
        <a href="{% url 'view_class' username=request.user.username coursename=event.related_class.course.name classname=event.related_class.class_name %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>
    </form>
</div>
{% endblock %}

core/templates/core/delete_profile.html
{% extends 'core/base.html' %}
{% block title %}Delete Profile{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Delete Profile</h2>
    <p>Are you sure you want to delete this profile: {{ profile.user.username }}? This action cannot be undone.</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Proceed</button>
        <a href="{% url 'home' profile.user.username %}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">Cancel</a>
    </form>
</div>
{% endblock %}

core/templates/core/edit_profile.html
<!-- templates/core/edit_profile.html -->

{% extends 'core/base.html' %}
{% block title %}Edit Profile{% endblock title %}
{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Edit Profile</h2>
    <div style="display: flex; flex-direction: row;">
        <p>Username: {{ user.username }}</p>
        <button><a href="{% url 'change_username' request.user.username %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-3 rounded mt-2">Change Username</a></button>
    </div>
    <div style="display: flex; flex-direction: row; margin-top: 1rem;">
        <p>Email: {{ user.email }}</p>
        <button><a href="{% url 'change_email' request.user.username %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-3 rounded mt-2">Change Email</a></button>
    </div>
    <div style="display: flex; flex-direction: row; margin-top: 1rem;">
        <button><a href="{% url 'change_password' request.user.username %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-3 rounded">Change Password</a></button>
    </div>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Attendance App{% endblock title %}
{% block content %}
<div class="container mx-auto px-4 py-8">
    <div class="text-center mb-8">
        <h1 class="text-4xl font-bold">Welcome to <small style="font-family:Calibri">W<b>H</b>ere</small>Are<i>YOU</i></h1>
        <p class="mt-4 text-lg text-gray-600">Empowering seamless attendance management with location-based check-ins.</p>
    </div>

    <!-- Feature Tiles -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        <div class="bg-white rounded-lg shadow-lg p-6">
            <img src="" alt="Event Management" class="w-full h-auto rounded-lg mb-4">
            <h2 class="text-xl font-bold mb-2">Event Management</h2>
            <p>Effortlessly create and manage events with detailed location constraints.</p>
        </div>
        <div class="bg-white rounded-lg shadow-lg p-6">
            <img src="" alt="Attendance Reports" class="w-full h-auto rounded-lg mb-4">
            <h2 class="text-xl font-bold mb-2">Comprehensive Reporting</h2>
            <p>Gain insights with comprehensive attendance reports and analytics.</p>
        </div>
    </div>

    <!-- Call to Action Buttons -->
    <div class="flex justify-center">
        <a href="{% url 'signup' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded mr-4">Sign Up Now!</a>
        <div style="flex-direction: row;">
        <div>Already have an account?</div> 
        <div><a href="{% url 'login' %}" class="text-gray-800 font-bold ">Log In</a></div>
       </div>
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %} 
{% block title %} Sign in {% endblock title %}
{% block content%}
  <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
     <h1 class="mb-6 text-3xl"> Sign in</h1>

     <form method="post" action=".">
        {% csrf_token %}
        
        <div class="mb-3">
             <label  class="inline-block mb-2" for="username">Username</label><br>
             {{form.username}}
        </div>


        <div class="mb-3">
            <label  class="inline-block mb-2" for="password1">Password</label><br>
            {{form.password}}
        </div>
        
       
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
           {% for field in form %}  
             {{field.errors}}\
            {% endfor %}

            {{form.non_field_errors}}
        </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover: bg-teal-700 rounded-xl text-white">submit</button>
     
    </form>
  </div>
{% endblock content %}